# permissions for end users to edit mcbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mcbinding-editor-role
rules:
- apiGroups:
  - machart.machart.rd
  resources:
  - mcbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machart.machart.rd
  resources:
  - mcbindings/status
  verbs:
  - get
