# permissions for end users to view mcbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mcbinding-viewer-role
rules:
- apiGroups:
  - machart.machart.rd
  resources:
  - mcbindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - machart.machart.rd
  resources:
  - mcbindings/status
  verbs:
  - get
