# permissions for end users to view mcclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mcclusters-viewer-role
rules:
- apiGroups:
  - machart.machart.rd
  resources:
  - mcclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - machart.machart.rd
  resources:
  - mcclusters/status
  verbs:
  - get
