# permissions for end users to edit mcclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mcclusters-editor-role
rules:
- apiGroups:
  - machart.machart.rd
  resources:
  - mcclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machart.machart.rd
  resources:
  - mcclusters/status
  verbs:
  - get
