# permissions for end users to edit mcmachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mcmachines-editor-role
rules:
- apiGroups:
  - machart.machart.rd
  resources:
  - mcmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machart.machart.rd
  resources:
  - mcmachines/status
  verbs:
  - get
