# permissions for end users to view mcmachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mcmachines-viewer-role
rules:
- apiGroups:
  - machart.machart.rd
  resources:
  - mcmachines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - machart.machart.rd
  resources:
  - mcmachines/status
  verbs:
  - get
